esphome:
  name: pipe-temperature-esp

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  - platform: esphome
    password: !secret api_password

wifi:
  ssid: "EA"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pipe-Temperature-Esp"
    password: !secret ap_password

captive_portal:
    
one_wire:
  - platform: gpio
    pin: D4 #GPIO5 #D1

sensor:
  - platform: dallas_temp
    address: 0x0100000001bf1528
    name: pipe_temperature_1
    update_interval: 60s
  - platform: dallas_temp
    address: 0x8e00000001efd228
    name: pipe_temperature_2
    update_interval: 60s
